version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.1.4

jobs:
  build_test:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout

      - run:
          name: Install backend dependencies
          command: |
            cd backend
            npm install

      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm install

  build_docker_images:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Build and push backend image
          command: |
            docker build -t yesiamkriti/test-circleci-backend:latest ./backend
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push yesiamkriti/test-circleci-backend:latest

      - run:
          name: Build and push frontend image
          command: |
            docker build -t yesiamkriti/test-circleci-frontend:latest ./frontend
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push yesiamkriti/test-circleci-frontend:latest

workflows:
  build_and_test:
    jobs:
      - build_test
      - build_docker_images:
          requires:
            - build_test
